[package]
name = "learn_blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "utils", version = "0.1.0"}
secp256k1 = "0.20.3"
bitcoin_hashes = "0.10.0"
